### PR TITLE
AddGenericReturnTypeToRelationsRector fix for chained relation call

### LINKED ISSUE #274: AddGenericReturnTypeToRelationsRector doesn't work if there is a chained method
`AddGenericReturnTypeToRelationsRector` doesn't work if there is a chained method.

## Works
```php
/**
 * @return \Illuminate\Database\Eloquent\Relations\HasMany<\App\Models\Sale, $this>
 */
public function sales(): HasMany
{
    return $this->hasMany(Sale::class);
}
```

## Doesn't work

```php
public function latestSale(): HasOne
{
    return $this->hasOne(Sale::class)->latestOfMany();
}

public function client(): BelongsTo
{
    return $this->belongsTo(Client::class)->withTrashed();
}

public function invoices(): HasMany
{
    return $this->hasMany(Invoice::class)->orderBy('process_date', 'desc');
}
```

### PR DESCRIPTION
**Pull request by rudiedirkx**
Fixes #274

### CODE REVIEW

**Comment by GeniJaho** [comment]
Thanks for the PR :smiley: Please add a test fixture for this case and we can merge it.

**Comment by rudiedirkx** [comment]
What? Where? How? Etc.

**Comment by GeniJaho** [comment]
😅  While this PR didn't break anything, we need a way to confirm it solves the issue. We need a test to prove that the changes work. 
There are test fixtures for the rule in `tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture`.
Please add two more, one in `NewGenerics` and one in `OldGenerics`, call them `relation-with-chained-method-calls.php.inc`, or something similar.
If this is too much, we can merge the PR and I'll complete the rest, don't worry.

**Comment by rudiedirkx** [comment]
What's the Old vs New distinction? The Laravel version, or PhpStan version, or other package version?

I think I got it working.

**Review by GeniJaho — APPROVED** [review]

**Comment by GeniJaho** [comment]
It's the Laravel version. From 11.15.0 we need to use the new Generics, as the old ones do not work well anymore after that version.
Basically, it's about the second model in the generic annotation, instead of using the class name like `User`, we need to use `$this` from that version onwards.

**Pull request merged**
