### PR TITLE
Add TChildModel for relations with childs in `AddGenericReturnTypeToRelationsRector`

### PR DESCRIPTION
**Pull request by rene-bos**

### CODE REVIEW

**Comment by rene-bos** [comment]
@driftingly This one is ready for review 🥳

**Comment by rene-bos** [comment]
Hmmm and now the Rector job fails on my real change 🤣  It checked rector-symfony and it [also does not work there](https://github.com/rectorphp/rector-symfony/actions/runs/3959145240/jobs/6782598867).

I just ran Rector manually and that fixes the problem. I think that is what everybody has to do then? I think we can improve the process there a bit later, as it is difficult to spot for contributers that they need to ran both `vendor/bin/rector process` and after that `composer run fix-cs` when the Rector job fails. I already asked ThomasVortuba on the PR from rector-symfny if he has a solution.. Hopefully he has one ;-)

For now, this one is green too, @driftingly  😄

**Comment by rene-bos** [comment]
The commit `[[ci-review] Rector Rectify](https://github.com/driftingly/rector-laravel/pull/82/commits/75aa0941ddd06ff4c75bff5f2ce06282399b3e91)` keeps popping up, maybe because I previously had an access token configured on my fork. You need to manually re-run the jobs I think (I don't have the powers for that).

**Comment by driftingly** [comment]
After I merged main the test reran and they were all green.
Thanks, @rene-bos for all your work on this.

**Comment by rene-bos** [comment]
You're welcome! thank you too for your time, @driftingly! Do you mind creating a new release with these fixes?

**Comment by driftingly** [comment]
@rene-bos released 0.15.0

**Comment by rene-bos** [comment]
> @rene-bos released 0.15.0

Thank you so much! 🙏

**Pull request merged**
