### PR TITLE
Route callable improvement

### PR DESCRIPTION
**Pull request by egorbwork**
Allows refactoring of routes using the array with `uses` as a single key and arrays that outside of the `name` key are using `middleware` one.

### CODE REVIEW

**Comment by driftingly** [comment]
@egorbwork are you able to get those workflows passing?

**Comment by egorbwork** [comment]
@driftingly  Will try as fast as possible.

**Comment by egorbwork** [comment]
@driftingly 
unit tests are fine now:
image

PHPstan I hope too.

**Comment by driftingly** [comment]
Thanks @egorbwork 🙌

**Pull request merged**
