### PR TITLE
Add Laravel Cashier 13 & 14 upgrade rules

### PR DESCRIPTION
**Pull request by GeniJaho**
Relates to https://github.com/driftingly/rector-laravel/issues/100

This PR introduces initial support for upgrading Laravel Cashier to version 13 and 14.

It only handles the method renames, since [other upgrades](https://github.com/laravel/cashier-stripe/blob/master/UPGRADE.md#upgrading-to-130-from-12x) are out of the scope (and capability) of Rector.

### CODE REVIEW

**Comment by GeniJaho** [comment]
Should I include the `LaravelCashierSetList` class somewhere? The CI fails since the class is currently unused in the project.

**Comment by driftingly** [comment]
@GeniJaho What do you think of having `config/sets/packages/cashier-13.php`?
If other package-specific sets are developed we could group them there?

**Comment by GeniJaho** [comment]
> 

Yes, that would be a lot better. Any idea to make the failing check to pass? The CashierSetList class is not used anywhere.

**Comment by driftingly** [comment]
@GeniJaho sorry, that was my suggestion for the set list.  Having something like what you did for Laravel 10:
https://github.com/driftingly/rector-laravel/blob/main/config/sets/level/up-to-laravel-100.php

**Comment by driftingly** [comment]
@GeniJaho is this ready?  
If it's ready to go can you merge in main and update the docs?
Thanks!

**Comment by GeniJaho** [comment]
@driftingly this is ready now, I updated the docs and main was merged. Not sure why that test failed before the merge though, I couldn't make it fail locally.

**Pull request merged**
