### PR TITLE
upgraded to rector/rector:^0.19.0

### PR DESCRIPTION
**Pull request by asugai**
Updated all references per https://github.com/rectorphp/rector/releases/tag/0.19.0

```
-use Rector\Core\
+use Rector\
```

### CODE REVIEW

**Comment by GeniJaho** [comment]
@asugai Thanks for the PR 😄 

I think you need to run `./vendor/bin/duster` to fix the Code Analysis issues.
Also, to make the PHPStan errors go away, you need to update the `phpstan.neon` file to replace the ignored errors for `Rector\\Core\\Contract\\Rector\\RectorInterface` and `Rector\\Core\\Reflection\\ReflectionResolver`.

Thank you ✌️

**Comment by asugai** [comment]
hey @GeniJaho - just saw these and applied the fixes

**Comment by driftingly** [comment]
@asugai Sorry, one last change, can you also update the Rector requirement here:
https://github.com/driftingly/rector-laravel/blob/main/build/composer-php-72.json

Thanks 🙌

**Comment by driftingly** [comment]
Thanks @asugai for your work on this 🙏 
I'll clean up in a separate PR.

**Pull request merged**
