### PR TITLE
Support updating an existing return type with generics

### PR DESCRIPTION
**Pull request by rene-bos**
Only supported if the existing PHPDoc return type is the same as the native return type. This way we ensure that we don't change types. 

Not updating of another type was already covered with a test. I added a test for the case when we can update the PHPDoc with only the generics.

### CODE REVIEW

**Comment by rene-bos** [comment]
Forgot to run PHPStan local before the last commit, will fix tomorrow.

**Comment by ratenfanger** [comment]
@driftingly This rule is ready to get reviewed (and hopefully to get merged!). I'm working on a further improvement of this rule which is build on top of this PR. I will prepare the PR if this one merged. That PR will fix the generics for BelongsTo and MorphTo, which both need a TChildModel specified.

**Comment by rene-bos** [comment]
@driftingly This rule is ready to get reviewed (and hopefully to get merged!). I'm working on a further improvement of this rule which is build on top of this PR. I will prepare the PR if this one merged. That PR will fix the generics for BelongsTo and MorphTo, which both need a TChildModel specified.

**Comment by driftingly** [comment]
Thanks @rene-bos!

**Pull request merged**
