### PR TITLE
Fix Rector job on PR to main repository

### PR DESCRIPTION
**Pull request by rene-bos**
Run only on PR's from branches on main repository (from core contributors), not on the forks or PR's from forks.

### CODE REVIEW

**Comment by driftingly** [comment]
I might have merged this too early. Sorry!

**Comment by rene-bos** [comment]
No problem! It should have created it as draft if I did not wanted it to get merged. Its  fine to be merged I think. If TomasVotruba agrees to move the check to rector.yaml we can just remove the if-statement.

For now we can keep the change here, as it will avoid errors like we had on #82.

**Comment by driftingly** [comment]
Should we revert https://github.com/driftingly/rector-laravel/pull/86/commits/3f57062b4ea94d83834e2024355e205bc31d9f1e

**Comment by rene-bos** [comment]
Yeah that's a good one. When we don't fix it it will pop up in a totally unrelated pull request some time 😉 Because of some strange hickup the change has already been committed to #82 ([[ci-review] Rector Rectify](https://github.com/driftingly/rector-laravel/pull/82/commits/75aa0941ddd06ff4c75bff5f2ce06282399b3e91)). 

Do you have time to check #82 and maybe create a release afterwards? At my company (Visma) we would love to have that change 😄. Avoids pinning to our fork and the associated maintenance of it. Sorry for making your day busy with all that PR's 😉

**Pull request merged**
